### PR TITLE
Add amami support

### PR DESCRIPTION
**Pull request by HazouPH**
From GitHub.com/spiritcroc

### CODE REVIEW

**Comment by SuperLamic** [comment]
Wasn't this for all rhine devices? https://github.com/SuperLamic/android_kernel_sony_msm8974/pull/6/commits/8f07bb735b5e211e08b92bdfe2b96c1dad39b565

can you get it into separate PR and use original?

Thanks

**Comment by SpiritCroc** [comment]
https://github.com/LineageOS/android_kernel_sony_msm8974/commit/5e419a9d68d928c8e1e6223e808398149c93d1e0

**Comment by HazouPH** [comment]
Yup, haven't looked at that, that way. Will do

**Comment by HazouPH** [comment]
Still needs the display update tho

**Comment by SuperLamic** [comment]
I know. Just make another PR. I won't work on it much now, I need new display to arrive from China...

**Comment by HazouPH** [comment]
display broken?, That could take some time from china :P

**Comment by SuperLamic** [comment]
Yeah, though I don't really understand what happened. I just took off my phone from pocket and the display was cracked... and touch doesn't really work + lots of ghost touches.

**Comment by HazouPH** [comment]
Could be done by many things. Hope u get it sorted out

**Pull request merged**
